#!/usr/bin/env python3
"""Generate an exhaustive inventory (aliases, functions, completions, apps, defaults)

Writes docs/INVENTORY.md containing machine-readable lists and a human-friendly summary.
"""
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
SCRIPTS = ROOT / "scripts"
DOCS = ROOT / "docs"
DOCS.mkdir(exist_ok=True)

def parse_aliases(file):
    aliases = []
    if not file.exists():
        return aliases
    with open(file, 'r') as fh:
        for line in fh:
            m = re.match(r"^\s*alias(?:\s+--\s+)?([^=\s]+)", line)
            if m:
                aliases.append(m.group(1))
    return aliases

def parse_functions(file):
    funcs = set()
    if not file.exists():
        return sorted(funcs)
    with open(file, 'r') as fh:
        for line in fh:
            m = re.match(r"^\s*function\s+([a-zA-Z0-9_]+)\s*\(", line)
            if m:
                funcs.add(m.group(1))
            else:
                m2 = re.match(r"^\s*([a-zA-Z0-9_]+)\s*\(\)\s*\{", line)
                if m2:
                    funcs.add(m2.group(1))
    return sorted(funcs)

def list_completions():
    completions_dir = ASSETS / "completions"
    if not completions_dir.exists():
        return []
    return sorted([p.name.lstrip('_') for p in completions_dir.iterdir() if p.is_file() and p.name.startswith('_')])

def find_print_installs():
    installs = []
    rx = re.compile(r'print_install\s+"([^"]+)"')
    for f in SCRIPTS.glob('*.sh'):
        with open(f, 'r') as fh:
            for line in fh:
                m = rx.search(line)
                if m:
                    installs.append((f.name, m.group(1)))
    return installs

def find_defaults():
    defaults = set()
    rx = re.compile(r"set_(?:user_)?default\s+([^\s]+)\s+([^\s]+)")
    for f in SCRIPTS.glob('*.sh'):
        with open(f, 'r') as fh:
            for line in fh:
                m = rx.search(line)
                if m:
                    domain = m.group(1)
                    key = m.group(2)
                    defaults.add((domain, key))
    return sorted(defaults)

def main():
    aliases_file = ASSETS / '.aliases'
    functions_file = ASSETS / '.functions'

    aliases = parse_aliases(aliases_file)
    functions = parse_functions(functions_file)
    # also include function names found inside scripts
    for f in SCRIPTS.glob('*.sh'):
        for name in parse_functions(f):
            if name not in functions:
                functions.append(name)
    functions = sorted(set(functions))

    completions = list_completions()
    installs = find_print_installs()
    defaults = find_defaults()

    out = DOCS / 'INVENTORY.md'
    with open(out, 'w') as fh:
        fh.write('# MachInit Inventory\n\n')
        fh.write('Generated by dev_scripts/generate_inventory.py\n\n')

        fh.write('## Aliases (assets/.aliases)\n')
        if aliases:
            for a in aliases:
                fh.write(f'- `{a}`\n')
        else:
            fh.write('- (none)\n')
        fh.write('\n')

        fh.write('## Functions (assets/.functions + scanned scripts)\n')
        if functions:
            for f in functions:
                fh.write(f'- `{f}()`\n')
        else:
            fh.write('- (none)\n')
        fh.write('\n')

        fh.write('## Completions (assets/completions)\n')
        if completions:
            for c in completions:
                fh.write(f'- `{c}`\n')
        else:
            fh.write('- (none)\n')
        fh.write('\n')

        fh.write('## App/install targets (detected via print_install in scripts/)\n')
        if installs:
            for s, app in installs:
                fh.write(f'- `{app}` (from `{s}`)\n')
        else:
            fh.write('- (none)\n')
        fh.write('\n')

        fh.write('## Defaults referenced (set_default / set_user_default)\n')
        if defaults:
            for domain, key in defaults:
                fh.write(f'- `{domain}` `{key}`\n')
        else:
            fh.write('- (none)\n')
        fh.write('\n')

        # small summary table
        fh.write('---\n')
        fh.write(f'- Aliases: {len(aliases)}\n')
        fh.write(f'- Functions: {len(functions)}\n')
        fh.write(f'- Completions: {len(completions)}\n')
        fh.write(f'- Install targets found: {len(installs)}\n')
        fh.write(f'- Default entries found: {len(defaults)}\n')

    print('WROTE:', out)

if __name__ == '__main__':
    main()
